#!/usr/bin/zsh

REPODIR="/home/emaballarin/repositories/"
cd "$REPODIR/algodes"

# Strassen: ASTRAGAL
cp -R -f ../ASTRAGAL ./code/ASTRAGAL


# Dijkstra: DijkStraike
cp -R -f ../DijkStraike ./code/dijkstra
